Repository IMAP-Science-Operations-Center/imap_processing, pull requests merged in 2023-08, with the labels that each got.

#51 Convert style guide from markdown to rst
  docs/source/development/style-guide.md
  docs/source/development/style-guide.rst
Labels: documentation

#53 Break up style guide into multiple pages
  docs/source/development/doc-overview.rst
  docs/source/development/index.rst
  docs/source/development/release-workflow.rst
  docs/source/development/style-guide.rst
  docs/source/development/style_guide/api-documentation.rst
  docs/source/development/style_guide/checklist-for-pull-requests.rst
  docs/source/development/style_guide/git-and-github-workflow.rst
  docs/source/development/style_guide/naming-conventions.rst
  docs/source/development/style_guide/poetry-environment.rst
  docs/source/development/style_guide/python-coding.rst
  docs/source/development/style_guide/security.rst
  docs/source/development/style_guide/style-guide.rst
  docs/source/development/style_guide/tools-and-library-recommendations.rst
  docs/source/development/style_guide/versioning.rst
Labels: documentation

#54 Document Versioning Schemes
  docs/source/development/style_guide/versioning.rst
Labels: documentation

#55 Document Release Workflow
  docs/source/development/release-workflow.rst
Labels: documentation

#72 XTCE decom with CoDICE example
  imap_processing/codice/CcsdsHeaderXtceGenerator.py
  imap_processing/codice/L0/ccsds-header.xml
  imap_processing/codice/L0/decom_python_example.py
  imap_processing/codice/L0/p_cod_aut_test.xml
  imap_processing/codice/RAW.bin
  imap_processing/codice/__init__.py
  imap_processing/codice/decom.py
  imap_processing/codice/generate_ccsds_header_xml.py
  imap_processing/codice/make_xtce.py
  imap_processing/codice/tests/__init__.py
  imap_processing/codice/tests/test_bin_data.py
Labels: enhancement, CoDICE, L0

#92 DOC: Update sphinx references
  .pre-commit-config.yaml
  docs/source/development/style-guide/poetry-environment.rst
  docs/source/development/style-guide/versioning.rst
  poetry.lock
Labels: documentation

#80 TST: Add coverage to testing pipeline
  .github/workflows/test.yml
  poetry.lock
  pyproject.toml
Labels: testing

#82 Adding documenation for pull request review standards
  docs/source/development/style-guide/checklist-for-pull-requests.rst
  docs/source/development/style-guide/review-standards.rst
  docs/source/development/style-guide/style-guide.rst
Labels: documentation

#84 Made tools directory and updated .toml
  imap_processing/codice/make_xtce.py
  poetry.lock
  pyproject.toml
  tools/xtce_generation/ccsds-header.xml
  tools/xtce_generation/ccsds_header_xtce_generator.py
  tools/xtce_generation/generate_ccsds_header_xml.py
Labels: documentation, L0
