Repository IMAP-Science-Operations-Center/imap_processing, pull requests merged in 2024-07, with the labels that each got.

#671 662 migrate remaining hi products to use cdfattributemanager
  imap_processing/cdf/config/imap_hi_global_cdf_attrs.yaml
  imap_processing/cdf/config/imap_hi_variable_attrs.yaml
  imap_processing/hi/l1a/histogram.py
  imap_processing/hi/l1a/science_direct_event.py
  imap_processing/tests/hi/test_l1a.py
Labels: Ins: Hi, CDF

#681 Fix Hi L1b test marked xfail
  imap_processing/tests/hi/test_hi_l1b.py
Labels: Ins: Hi

#659 Add mypy Pre-commit Hook and Fix tools folder Pt.1
  .pre-commit-config.yaml
  pyproject.toml
  tools/metadata_generation/metadata_generator.py
  tools/spice/spice_examples.py
  tools/spice/spice_utils.py
  tools/xtce_generation/ccsds_header_xtce_generator.py
  tools/xtce_generation/telemetry_generator.py
  tools/xtce_generation/xtce_generator_codice.py
  tools/xtce_generation/xtce_generator_glows.py
  tools/xtce_generation/xtce_generator_hi.py
  tools/xtce_generation/xtce_generator_hit.py
  tools/xtce_generation/xtce_generator_lo.py
  tools/xtce_generation/xtce_generator_mag.py
  tools/xtce_generation/xtce_generator_swapi.py
  tools/xtce_generation/xtce_generator_swe.py
  tools/xtce_generation/xtce_generator_template.py
Labels: Repo: Documentation, Repo: Testing

#661 Add mypy Pre-Commit Hook for files Pt.2
  imap_processing/cdf/cdf_attribute_manager.py
  imap_processing/cdf/imap_cdf_manager.py
  imap_processing/cdf/utils.py
  imap_processing/cli.py
  imap_processing/decom.py
  imap_processing/utils.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#663 Add mypy Pre-Commit For Ultra Pt.3
  .pre-commit-config.yaml
  imap_processing/ultra/l0/decom_tools.py
  imap_processing/ultra/l0/decom_ultra.py
  imap_processing/ultra/l0/ultra_utils.py
  imap_processing/ultra/l1a/ultra_l1a.py
  imap_processing/ultra/l1b/badtimes.py
  imap_processing/ultra/l1b/cullingmask.py
  imap_processing/ultra/l1b/de.py
  imap_processing/ultra/l1b/extendedspin.py
  imap_processing/ultra/l1b/ultra_l1b.py
  imap_processing/ultra/l1c/pset.py
  imap_processing/ultra/l1c/ultra_l1c.py
  imap_processing/ultra/utils/ultra_l1_utils.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#666 Add mypy Pre-Commit for swe Pt.4
  .pre-commit-config.yaml
  imap_processing/cli.py
  imap_processing/swe/l0/decom_swe.py
  imap_processing/swe/l1a/swe_l1a.py
  imap_processing/swe/l1a/swe_science.py
  imap_processing/swe/l1b/swe_l1b.py
  imap_processing/swe/l1b/swe_l1b_science.py
  imap_processing/swe/utils/swe_utils.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#667 Add mypy Pre-commit for swapi Pt.5
  imap_processing/swapi/l1/swapi_l1.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#668 Add Pre-Commit For mag Pt.6
  imap_processing/mag/l0/mag_l0_data.py
  imap_processing/mag/l1a/mag_l1a.py
  imap_processing/mag/l1a/mag_l1a_data.py
  imap_processing/mag/l1b/mag_l1b.py
  imap_processing/mag/l1c/mag_l1c.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#669 Add mypy Pre-Commit For Lo Pt.7
  imap_processing/cdf/global_attrs.py
  imap_processing/lo/l0/data_classes/science_counts.py
  imap_processing/lo/l0/data_classes/science_direct_events.py
  imap_processing/lo/l0/data_classes/star_sensor.py
  imap_processing/lo/l0/utils/binary_string.py
  imap_processing/lo/l0/utils/bit_decompression.py
  imap_processing/lo/l0/utils/lo_base.py
  imap_processing/lo/l1a/lo_data_container.py
  imap_processing/lo/l1a/lo_l1a.py
  imap_processing/lo/l1a/lo_l1a_write_cdfs.py
  imap_processing/lo/l1b/lo_l1b.py
  imap_processing/lo/l1c/lo_l1c.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#670 Add mypy Pre-Commit For idex Pt.8
  imap_processing/idex/idex_packet_parser.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#673 Add mypy Pre-Commit For ialirt Pt.9
  imap_processing/ialirt/l0/decom_ialirt.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#674 Add mypy Pre-Commit For hi & hit Pt.10
  imap_processing/decom.py
  imap_processing/hi/l0/decom_hi.py
  imap_processing/hi/l1a/hi_l1a.py
  imap_processing/hi/l1a/science_direct_event.py
  imap_processing/hi/l1b/hi_l1b.py
  imap_processing/hi/l1c/hi_l1c.py
  imap_processing/hi/utils.py
  imap_processing/hit/hit_cdf_attrs.py
  imap_processing/hit/l0/data_classes/housekeeping.py
  imap_processing/hit/l0/utils/hit_base.py
  imap_processing/hit/l1a/hit_l1a.py
  imap_processing/hit/l1b/hit_l1b.py
  imap_processing/ultra/l1c/histogram.py
  imap_processing/utils.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#676 Add mypy Pre-Commit for glows Pt.11
  imap_processing/glows/l0/glows_l0_data.py
  imap_processing/glows/l1a/glows_l1a.py
  imap_processing/glows/l1a/glows_l1a_data.py
  imap_processing/glows/l1b/glows_l1b.py
  imap_processing/glows/l1b/glows_l1b_data.py
  imap_processing/glows/utils/constants.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#678 Add mypy Pre-Commit for codice Pt.12 Last
  imap_processing/codice/codice_l0.py
  imap_processing/codice/codice_l1a.py
  imap_processing/codice/codice_l1b.py
  imap_processing/codice/decompress.py
  imap_processing/codice/utils.py
  pyproject.toml
Labels: Repo: Documentation, Repo: Testing

#654 Xtce combined
  imap_processing/ccsds/excel_to_xtce.py
  imap_processing/tests/ccsds/test_excel_to_xtce.py
  poetry.lock
  pyproject.toml
  tools/tests/test_xtce_generator_template.py
  tools/xtce_generation/26850.02-TLMDEF-04.xlsx
  tools/xtce_generation/TLM_SWP_20231006-121021.xlsx
  tools/xtce_generation/ccsds_header_xtce_generator.py
  tools/xtce_generation/telemetry_generator.py
  tools/xtce_generation/xtce_generator_codice.py
  tools/xtce_generation/xtce_generator_glows.py
  tools/xtce_generation/xtce_generator_hi.py
  tools/xtce_generation/xtce_generator_hit.py
  tools/xtce_generation/xtce_generator_lo.py
  tools/xtce_generation/xtce_generator_mag.py
  tools/xtce_generation/xtce_generator_swapi.py
  tools/xtce_generation/xtce_generator_swe.py
  tools/xtce_generation/xtce_generator_template.py
Labels: Level: L0

#687 ENH/MNT: Add a common initial dataset creation routine
  imap_processing/cdf/utils.py
  imap_processing/hi/l1a/hi_l1a.py
  imap_processing/hi/l1a/histogram.py
  imap_processing/hi/l1a/housekeeping.py
  imap_processing/hi/l1a/science_direct_event.py
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/tests/hi/test_l1a.py
  imap_processing/tests/swapi/test_swapi_l1.py
  imap_processing/utils.py
Labels: enhancement

#684 682 imap hi use imapcdfattributes instead of cdfattributemanager
  imap_processing/hi/l1a/science_direct_event.py
  imap_processing/hi/l1b/hi_l1b.py
  imap_processing/hi/l1c/hi_l1c.py
Labels: Ins: Hi, CDF

#704 switched SWAPI CDF attrs to use YAML
  imap_processing/cdf/config/imap_swapi_global_cdf_attrs.yaml
  imap_processing/cdf/config/imap_swapi_variable_attrs.yaml
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/swapi/swapi_cdf_attrs.py
  imap_processing/tests/swapi/test_swapi_l1.py
Labels: Ins: SWAPI, Level: L1, CDF

#714 Cleanup CDF dataclass
  imap_processing/cdf/__init__.py
  imap_processing/cdf/config/imap_constant_attrs.yaml
  imap_processing/cdf/config/imap_hi_global_cdf_attrs.yaml
  imap_processing/cdf/config/imap_ultra_global_cdf_attrs.yaml
  imap_processing/cdf/config/imap_ultra_l1a_variable_attrs.yaml
  imap_processing/cdf/defaults.py
  imap_processing/cdf/global_attrs.py
  imap_processing/cdf/imap_cdf_manager.py
  imap_processing/codice/utils.py
  imap_processing/common_cdf_attrs.py
  imap_processing/hi/hi_cdf_attrs.py
  imap_processing/hi/l1a/housekeeping.py
  imap_processing/hit/hit_cdf_attrs.py
  imap_processing/lo/l0/data_classes/science_direct_events.py
  imap_processing/lo/l1a/lo_cdf_attrs.py
  imap_processing/lo/l1a/lo_l1a_write_cdfs.py
  imap_processing/mag/l0/decom_mag.py
  imap_processing/mag/l1a/mag_l1a.py
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/tests/cdf/test_attr_classes.py
  imap_processing/tests/cdf/test_imap_cdf_manager.py
  imap_processing/tests/cdf/test_utils.py
  imap_processing/tests/lo/test_lo_l1a_write_cdfs.py
  imap_processing/tests/lo/test_science_direct_events.py
  imap_processing/tests/ultra/unit/test_decom_apid_896.py
  imap_processing/tests/ultra/unit/test_ultra_l1a.py
  imap_processing/ultra/l0/ultra_utils.py
  imap_processing/ultra/l1a/ultra_l1a.py
  imap_processing/ultra/ultra_cdf_attrs.py
  imap_processing/utils.py
Labels: enhancement, CDF

#718 Refactor epoch attrs
  imap_processing/cdf/__init__.py
  imap_processing/cdf/config/imap_codice_l1a_variable_attrs.yaml
  imap_processing/cdf/config/imap_codice_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_glows_l1a_variable_attrs.yaml
  imap_processing/cdf/config/imap_glows_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_hi_variable_attrs.yaml
  imap_processing/cdf/config/imap_hit_l1a_variable_attrs.yaml
  imap_processing/cdf/config/imap_hit_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_idex_l1_variable_attrs.yaml
  imap_processing/cdf/config/imap_lo_l1a_variable_attrs.yaml
  imap_processing/cdf/config/imap_lo_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_lo_l1c_variable_attrs.yaml
  imap_processing/cdf/config/imap_mag_l1_variable_attrs.yaml
  imap_processing/cdf/config/imap_swe_l1a_variable_attrs.yaml
  imap_processing/cdf/config/imap_swe_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_ultra_l1b_variable_attrs.yaml
  imap_processing/cdf/config/imap_ultra_l1c_variable_attrs.yaml
  imap_processing/codice/codice_l1a.py
  imap_processing/codice/utils.py
  imap_processing/glows/l1b/glows_l1b.py
  imap_processing/hi/l1a/histogram.py
  imap_processing/hi/l1a/science_direct_event.py
  imap_processing/hi/l1c/hi_l1c.py
  imap_processing/lo/l1a/lo_l1a_write_cdfs.py
  imap_processing/mag/l0/decom_mag.py
  imap_processing/mag/l1a/mag_l1a.py
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/tests/cdf/test_utils.py
  imap_processing/tests/glows/test_glows_l1b.py
  imap_processing/tests/hi/test_hi_l1c.py
  imap_processing/ultra/utils/ultra_l1_utils.py
  imap_processing/utils.py
Labels: enhancement, CDF

#723 MNT: Minimize the datatypes created from space_packet_parser
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/tests/test_utils.py
  imap_processing/utils.py
Labels: enhancement

#721 SWAPI l2 Implementation - counts to rate
  imap_processing/cdf/config/imap_swapi_global_cdf_attrs.yaml
  imap_processing/cdf/config/imap_swapi_variable_attrs.yaml
  imap_processing/cli.py
  imap_processing/swapi/l1/swapi_l1.py
  imap_processing/swapi/l2/__init__.py
  imap_processing/swapi/l2/swapi_l2.py
  imap_processing/tests/swapi/conftest.py
  imap_processing/tests/swapi/test_swapi_decom.py
  imap_processing/tests/swapi/test_swapi_l1.py
  imap_processing/tests/swapi/test_swapi_l2.py
Labels: Ins: SWAPI, Level: L2, CDF

#694 Bitflags
  imap_processing/quality_flags.py
  imap_processing/tests/test_quality_flags.py
Labels: Level: L1
