Repository IMAP-Science-Operations-Center/imap_processing, pull requests merged in 2024-02, with the labels that each got.

#329 Updates to API docs
  docs/source/code-documentation/tools/imap-data-access.rst
  docs/source/code-documentation/tools/index.rst
  docs/source/data-access-api/index.rst
  docs/source/data-access-api/openapi.yml
Labels: documentation

#331 Use "extension" instead of "format" in naming conventions
  docs/source/development-guide/style-guide/naming-conventions.rst
Labels: documentation

#332 v0.2.0 Release
  imap_processing/__init__.py
  pyproject.toml
Labels: Release

#336 FIX: Make sure configurations are synced between packages
  imap_processing/__init__.py
  imap_processing/cdf/utils.py
  imap_processing/cli.py
  imap_processing/tests/conftest.py
  imap_processing/tests/test_data_access.py
Labels: bug

#337 Fix IDEX and HIT tests
  imap_processing/tests/hit/test_hit_decom.py
  imap_processing/tests/idex/imap_idex_l0_raw_20230725_20230725_v01-00.pkts
  imap_processing/tests/idex/test_decom.py
  imap_processing/tests/idex/test_l1_cdfs.py
Labels: testing

#334 Updated naming conventions for CoDICE
  docs/source/development-guide/style-guide/naming-conventions.rst
Labels: documentation, CoDICE

#347 L0 Decom Ultra
  imap_processing/tests/ultra/test_data/l0/FM45_7P_Phi0.0_BeamCal_LinearScan_phi0.04_theta-0.01_20230821T121304.CCSDS
  imap_processing/tests/ultra/test_data/l0/FM45_TV_Cycle6_Hot_Ops_Front212_20240124T063837.CCSDS
  imap_processing/tests/ultra/test_data/l0/ultra45_raw_sc_enaphxtofhangimg_FM45_TV_Cycle6_Hot_Ops_Front212_20240124T063837.csv
  imap_processing/tests/ultra/test_data/l0/ultra45_raw_sc_ultrarawimgevent_FM45_7P_Phi00_BeamCal_LinearScan_phi004_theta-001_20230821T121304.csv
  imap_processing/tests/ultra/unit/conftest.py
  imap_processing/tests/ultra/unit/test_decom_apid_880.py
  imap_processing/tests/ultra/unit/test_decom_apid_881.py
  imap_processing/tests/ultra/unit/test_decom_apid_883.py
  imap_processing/tests/ultra/unit/test_decom_apid_896.py
  imap_processing/ultra/l0/decom_tools.py
  imap_processing/ultra/l0/decom_ultra.py
  imap_processing/ultra/l0/ultra_utils.py
  imap_processing/ultra/packet_definitions/P_U45_IMAGE_RATES.xml
  imap_processing/ultra/packet_definitions/P_U45_IMG_ENA_PHXTOF_HI_ANG.xml
  imap_processing/ultra/packet_definitions/P_U45_IMG_RAW_EVENTS.xml
  imap_processing/ultra/packet_definitions/ULTRA_SCI_COMBINED.xml
Labels: IMAP-Ultra, L0

#352 Create l1a cdfs for auxiliary data packet
  imap_processing/tests/codice/test_codice_l1a.py
  imap_processing/tests/idex/test_l1_cdfs.py
  imap_processing/tests/mag/test_mag_decom.py
  imap_processing/tests/ultra/unit/test_ultra_l1a.py
  imap_processing/ultra/__init__.py
  imap_processing/ultra/l1a/ultra_l1a.py
  imap_processing/ultra/ultra_cdf_attrs.py
  poetry.lock
  pyproject.toml
Labels: IMAP-Ultra
