Repository IMAP-Science-Operations-Center/imap_processing, pull requests merged in 2025-09, with the labels that each got.

#2134 CoDICE L2 - add function for geometric factors
  imap_processing/cdf/config/imap_codice_global_cdf_attrs.yaml
  imap_processing/codice/codice_l2.py
  imap_processing/codice/constants.py
  imap_processing/codice/data/lo_stepping_values.csv
  imap_processing/tests/codice/test_codice_l2.py
Labels: Ins: CoDICE, Level: L2

#2178 Lo L1B - add ESA mode and fix spin cycle in ADE
  imap_processing/cli.py
  imap_processing/lo/l1b/lo_l1b.py
  imap_processing/tests/lo/test_anc/imap_lo_sweep-table-small_20250101_20260301_v001.csv
  imap_processing/tests/lo/test_lo_l1b.py
Labels: Ins: Lo, Level: L1

#2177 2111 mag l1d l2 use correct instrument frame for geometry
  .pre-commit-config.yaml
  imap_processing/ialirt/l0/ialirt_spice.py
  imap_processing/mag/l2/mag_l2_data.py
  imap_processing/spice/geometry.py
  imap_processing/spice/pointing_frame.py
  imap_processing/tests/conftest.py
  imap_processing/tests/glows/test_glows_l1b.py
  imap_processing/tests/ialirt/unit/test_ialirt_spice.py
  imap_processing/tests/ialirt/unit/test_parse_mag.py
  imap_processing/tests/mag/test_mag_l1d.py
  imap_processing/tests/spice/test_data/imap_001.tf
  imap_processing/tests/spice/test_data/imap_wkcp.tf
  imap_processing/tests/spice/test_geometry.py
  imap_processing/tests/spice/test_pointing_frame.py
  imap_processing/tests/spice/test_spin.py
  imap_processing/tests/ultra/unit/test_ultra_l1b_annotated.py
Labels: Ins: MAG, SPICE

#2171 2114 hilo l2 flux correction predictor corrector scheme
  imap_processing/ena_maps/utils/corrections.py
  imap_processing/tests/ena_maps/conftest.py
  imap_processing/tests/ena_maps/data/imap_hi_90sensor-esa-eta-fit-factors_20240101_v001.csv
  imap_processing/tests/ena_maps/data/imap_lo_esa-eta-fit-factors_20240101_v001.csv
  imap_processing/tests/ena_maps/test_corrections.py
Labels: Ins: Hi, Ins: Lo

#2184 Add Lo l2 backgrounds
  imap_processing/lo/l2/lo_l2.py
  imap_processing/tests/lo/test_lo_l2.py
Labels: Ins: Lo, Level: L2

#2187 I-ALiRT - minor bug fix
  imap_processing/ialirt/utils/create_xarray.py
Labels: I-ALiRT

#2195 Lo l2 sputtering
  imap_processing/lo/l2/lo_l2.py
  imap_processing/tests/lo/test_lo_l2.py
Labels: Ins: Lo, Level: L2

#2197 Lo l2 bootstrap
  imap_processing/lo/l2/lo_l2.py
  imap_processing/tests/lo/test_lo_l2.py
Labels: Ins: Lo, Level: L2

#2222 MNT: Add generation information to write_cdf routine
  imap_processing/cdf/utils.py
Labels: CDF

#2227 2138 hi l2 combine calibration products
  imap_processing/hi/hi_l2.py
  imap_processing/tests/hi/test_hi_l2.py
Labels: Ins: Hi

#2236 2218 hi l2 integrate flux correction
  docs/source/conf.py
  imap_processing/cli.py
  imap_processing/hi/hi_l2.py
  imap_processing/tests/hi/test_hi_l2.py
  imap_processing/tests/test_cli.py
Labels: Ins: Hi

#2243 2217 updates to ena l2 attributes
  imap_processing/cdf/config/imap_constant_attrs.yaml
  imap_processing/cdf/config/imap_enamaps_l2-common_variable_attrs.yaml
  imap_processing/cdf/config/imap_enamaps_l2-healpix_variable_attrs.yaml
  imap_processing/cdf/config/imap_enamaps_l2-rectangular_variable_attrs.yaml
  imap_processing/ena_maps/ena_maps.py
  imap_processing/hi/hi_l2.py
  imap_processing/tests/ena_maps/test_ena_maps.py
  imap_processing/tests/hi/test_hi_l2.py
  imap_processing/tests/ultra/unit/test_ultra_l2.py
  imap_processing/ultra/l2/ultra_l2.py
Labels: Ins: Hi, Ins: Lo, Ins: Ultra, CDF
